version: '3'

services:
  db:
    container_name: db_desafio
    hostname: db
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:latest
    networks:
      - network
    ports:
      - 3306:3306
    volumes:
      - ./mysqldata:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=desafio_ddd
      - MYSQL_USER=desafio
      - MYSQL_PASSWORD=123456

networks:
  network:
    driver: bridge
